# Generated by Django 5.2.4 on 2025-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=25)),
            ],
        ),
    ]
